Lab1


In [362]:
import numpy as np
import pandas as pd

# Static array
np.array([[1,2,3,4,5],[55,66,77,88,99],[111,222,333,444,555]])

array([[  1,   2,   3,   4,   5],
       [ 55,  66,  77,  88,  99],
       [111, 222, 333, 444, 555]])

In [363]:
# Random array (3x5 matrix)
np.random.rand(3,5)

array([[0.4103283 , 0.78390192, 0.27693338, 0.19236706, 0.20777768],
       [0.90634607, 0.90233451, 0.92853245, 0.36031992, 0.31300582],
       [0.93567505, 0.96927176, 0.51186993, 0.86604605, 0.61202164]])

In [364]:
# Array with zero integers 5x4 matrix
np.zeros((5,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [365]:
# Array with float ones 3x3 matrix
np.ones((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [366]:
# Array with 5 integers from 0 to 100
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [367]:
# Array with 5 float numbers from 0 to 2
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [368]:
# Random integer array 30x30 matrix
np.random.randint(0,100,(10,10))

array([[57, 48, 13, 72, 46, 53,  6, 99, 69, 99],
       [68, 17, 37, 45, 41, 35, 58, 80, 77, 97],
       [71, 63, 58, 98, 27, 63, 35, 27, 70, 66],
       [63, 91, 48, 73, 44, 60, 27, 89, 37, 52],
       [16, 44, 35, 22, 33, 17, 12, 81, 95, 56],
       [50,  3, 48, 68, 35,  5, 87, 78,  9, 62],
       [49,  5, 77, 92, 13, 61, 25, 11, 47, 38],
       [13, 11, 14, 28, 64, 25, 71, 60, 26, 59],
       [95, 69, 91, 29, 58, 75, 68,  8, 22, 80],
       [67, 81, 35, 34, 48, 16, 67, 84, 16, 60]])

In [369]:
#Empty array 3x3 matrix
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [370]:
a = np.array([1,4,5,6,7])
matrix = np.array([[1,2,3,4,5],[55,66,77,88,99],[111,222,333,444,555]])

a[-1]

7

In [371]:
a[0:3]

array([1, 4, 5])

In [372]:
a[3]

6

In [373]:
matrix[1:3,2:4]

array([[ 77,  88],
       [333, 444]])

In [374]:
matrix[2][3]

444

In [375]:
a + 23

array([24, 27, 28, 29, 30])

In [376]:
matrix * 0.5

array([[  0.5,   1. ,   1.5,   2. ,   2.5],
       [ 27.5,  33. ,  38.5,  44. ,  49.5],
       [ 55.5, 111. , 166.5, 222. , 277.5]])

In [377]:
a ** 12

array([          1,    16777216,   244140625, -2118184960,   956385313],
      dtype=int32)

In [378]:
np.add.reduce(a)

23

In [379]:
np.add.accumulate(a)

array([ 1,  5, 10, 16, 23])

In [380]:
np.divide.outer(a,a)

array([[1.        , 0.25      , 0.2       , 0.16666667, 0.14285714],
       [4.        , 1.        , 0.8       , 0.66666667, 0.57142857],
       [5.        , 1.25      , 1.        , 0.83333333, 0.71428571],
       [6.        , 1.5       , 1.2       , 1.        , 0.85714286],
       [7.        , 1.75      , 1.4       , 1.16666667, 1.        ]])

In [381]:
data = pd.read_csv('iris.csv')
petals = data[['petal_width']]

#max petal width
np.max(petals)

2.5

In [382]:
#min petal width
np.min(petals)

0.1

In [383]:
#mean petal width
np.mean(petals)

1.1986666666666668

In [384]:
#variance petal width
np.var(petals)

F:\univer\data\py-lab1\venv\Lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


petal_width    0.578532
dtype: float64

In [385]:
#standard deviation petal width
np.std(petals)

F:\univer\data\py-lab1\venv\Lib\site-packages\numpy\core\fromnumeric.py:3643: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


petal_width    0.760613
dtype: float64

In [386]:
#median petal width
np.median(petals)

1.3

In [387]:
#25 percentile petal width
np.percentile(petals, 25)

0.3

In [388]:
#75 percentile petal width
np.percentile(petals, 75)

1.8