Lab1


In [1]:
import numpy as np
import pandas as pd

# Static array
np.array([[1,2,3,4,5],[55,66,77,88,99],[111,222,333,444,555]])

array([[  1,   2,   3,   4,   5],
       [ 55,  66,  77,  88,  99],
       [111, 222, 333, 444, 555]])

In [2]:
# Random array (3x5 matrix)
np.random.rand(3,5)

array([[0.14069928, 0.28087293, 0.42905474, 0.5496995 , 0.96802396],
       [0.50225572, 0.56185533, 0.64174831, 0.65716351, 0.74370163],
       [0.20376007, 0.67495182, 0.87546039, 0.06881503, 0.64875525]])

In [3]:
# Array with zero integers 5x4 matrix
np.zeros((5,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
# Array with float ones 3x3 matrix
np.ones((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# Array with 5 integers from 0 to 100
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [6]:
# Array with 5 float numbers from 0 to 2
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [7]:
# Random integer array 10x10 matrix
np.random.randint(0,100,(10,10))

array([[55,  6, 12, 50, 59, 64, 18,  9, 67, 19],
       [95, 48, 68, 61, 92, 55, 82, 52, 36, 57],
       [52, 29, 37, 12, 91, 57, 89, 10, 62,  0],
       [16, 43, 51, 98, 59, 89,  3, 17, 61, 71],
       [23, 18, 15, 41, 11, 20, 46,  8, 17, 91],
       [25, 25, 26, 31, 11, 65, 11, 43, 11, 13],
       [55, 94, 14, 66, 79, 63, 57, 35, 83, 47],
       [45, 62, 13, 10, 84, 37, 81, 49, 53, 22],
       [24, 98, 49, 84, 96, 45, 32, 91, 92, 67],
       [66, 86, 96, 87, 29, 21,  4, 81, 90,  5]])

In [8]:
#Empty array 3x3 matrix
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.array([1,4,5,6,7])
matrix = np.array([[1,2,3,4,5],[55,66,77,88,99],[111,222,333,444,555]])

a[-1]

7

In [10]:
a[0:3]

array([1, 4, 5])

In [11]:
a[3]

6

In [12]:
matrix[1:3,2:4]

array([[ 77,  88],
       [333, 444]])

In [13]:
matrix[2][3]

444

In [14]:
a + 23

array([24, 27, 28, 29, 30])

In [15]:
matrix * 0.5

array([[  0.5,   1. ,   1.5,   2. ,   2.5],
       [ 27.5,  33. ,  38.5,  44. ,  49.5],
       [ 55.5, 111. , 166.5, 222. , 277.5]])

In [16]:
a ** 12

array([          1,    16777216,   244140625, -2118184960,   956385313],
      dtype=int32)

In [17]:
np.add.reduce(a)

23

In [18]:
np.add.accumulate(a)

array([ 1,  5, 10, 16, 23])

In [19]:
np.divide.outer(a,a)

array([[1.        , 0.25      , 0.2       , 0.16666667, 0.14285714],
       [4.        , 1.        , 0.8       , 0.66666667, 0.57142857],
       [5.        , 1.25      , 1.        , 0.83333333, 0.71428571],
       [6.        , 1.5       , 1.2       , 1.        , 0.85714286],
       [7.        , 1.75      , 1.4       , 1.16666667, 1.        ]])

In [20]:
data = pd.read_csv('iris.csv')
petals = data[['petal_width']]

#max petal width
np.max(petals)

2.5

In [21]:
#min petal width
np.min(petals)

0.1

In [22]:
#mean petal width
np.mean(petals)

1.1986666666666668

In [23]:
#variance petal width
np.var(petals)

F:\univer\data\py-lab1\venv\Lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


petal_width    0.578532
dtype: float64

In [24]:
#standard deviation petal width
np.std(petals)

F:\univer\data\py-lab1\venv\Lib\site-packages\numpy\core\fromnumeric.py:3643: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


petal_width    0.760613
dtype: float64

In [25]:
#median petal width
np.median(petals)

1.3

In [26]:
#25 percentile petal width
np.percentile(petals, 25)

0.3

In [27]:
#75 percentile petal width
np.percentile(petals, 75)

1.8